# -*- coding: utf-8 -*-
"""3ETL_Full_BDExoplanetas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8aeGgDhHbsOdWS7ksUS3_zNanDTMG3X
"""

#!pip install pandas requests

import requests
import pandas as pd
from io import StringIO

query = """
SELECT
    pl_name,
    hostname,
    pl_masse,
    pl_rade,
    pl_orbper,
    pl_orbsmax,
    st_mass,
    st_rad,
    st_teff,
    sy_snum,
    sy_pnum,
    disc_year,
    discoverymethod,
    disc_facility,
    disc_telescope,
    disc_instrument
FROM pscomppars
"""

url = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync"

params = {
    "query": query,
    "format": "csv"
}

respuesta = requests.get(url, params=params)

respuesta.status_code

df = pd.read_csv(
    StringIO(respuesta.text)
)

df.head()

df.shape

len(df)

df.info()

df.to_csv(
    "exoplanetas_nasa.csv",
    index=False
)

df.isna().sum()

df.isna().sum().sort_values(ascending=False)

df["hostname"].nunique()

df["hostname"].value_counts().head(10)

estrellas = df[
    [
        "hostname",
        "st_mass",
        "st_rad",
        "st_teff"
    ]
].copy()

estrellas["hostname"].nunique()

len(estrellas)

estrellas = estrellas.drop_duplicates(
    subset=["hostname"]
)

len(estrellas)

estrellas["hostname"].nunique()

estrellas = estrellas.reset_index(drop=True)

estrellas.insert(
    0,
    "id_estrella",
    range(1, len(estrellas) + 1)
)

estrellas = estrellas.rename(columns={
    "hostname": "nombre",
    "st_mass": "masa",
    "st_rad": "radio",
    "st_teff": "temperatura"
})

planetas = df[
    [
        "pl_name",
        "hostname",
        "pl_masse",
        "pl_rade",
        "pl_orbper",
        "pl_orbsmax"
    ]
].copy()

planetas = planetas.rename(columns={
    "pl_name": "nombre",
    "pl_masse": "masa",
    "pl_rade": "radio",
    "pl_orbper": "periodo_orbital",
    "pl_orbsmax": "semieje_mayor"
})

planetas = planetas.merge(
    estrellas[["id_estrella", "nombre"]],
    left_on="hostname",
    right_on="nombre",
    how="left"
)

planetas.head()

planetas = planetas.drop(
    columns=["nombre_y"]
)

planetas = planetas.rename(
    columns={"nombre_x": "nombre"}
)

planetas.head()

planetas["id_estrella"].isna().sum()

planetas = planetas.reset_index(drop=True)

planetas.insert(
    0,
    "id_planeta",
    range(1, len(planetas) + 1)
)

planetas = planetas.drop(
    columns=["hostname"]
)

planetas.head()

"""PLANETA
id_planeta
id_estrella     ← FK
nombre
masa
radio
periodo_orbital
semieje_mayor
"""

descubrimientos = df[
    [
        "pl_name",
        "disc_year",
        "discoverymethod",
        "disc_facility",
        "disc_telescope",
        "disc_instrument"
    ]
].copy()

descubrimientos = descubrimientos.rename(columns={
    "pl_name": "planeta",
    "disc_year": "año",
    "discoverymethod": "metodo",
    "disc_facility": "instalacion",
    "disc_telescope": "telescopio",
    "disc_instrument": "instrumento"
})

descubrimientos = descubrimientos.merge(
    planetas[["id_planeta", "nombre"]],
    left_on="planeta",
    right_on="nombre",
    how="left"
)

descubrimientos.head()

descubrimientos = descubrimientos.drop(
    columns=["nombre"]
)

descubrimientos = descubrimientos.rename(
    columns={"planeta": "nombre_planeta"}
)

descubrimientos.head()

telescopios = df[
    [
        "disc_facility",
        "disc_telescope",
        "disc_instrument"
    ]
].drop_duplicates()

telescopios = telescopios.rename(columns={
    "disc_facility": "instalacion",
    "disc_telescope": "nombre",
    "disc_instrument": "instrumento"
})

telescopios = telescopios.reset_index(drop=True)

telescopios.insert(
    0,
    "id_telescopio",
    range(1, len(telescopios) + 1)
)

telescopios.head()

descubrimientos = descubrimientos.merge(
    telescopios[
        [
            "id_telescopio",
            "nombre",
            "instalacion",
            "instrumento"
        ]
    ],
    left_on=[
        "telescopio",
        "instalacion",
        "instrumento"
    ],
    right_on=[
        "nombre",
        "instalacion",
        "instrumento"
    ],
    how="left"
)

descubrimientos = descubrimientos.reset_index(drop=True)

descubrimientos.insert(
    0,
    "id_descubrimiento",
    range(1, len(descubrimientos) + 1)
)

descubrimientos = descubrimientos[
    [
        "id_descubrimiento",
        "id_planeta",
        "id_telescopio",
        "año",
        "metodo"
    ]
]

descubrimientos.head()

estrellas.to_csv(
    "estrella.csv",
    index=False
)

planetas.to_csv(
    "planeta.csv",
    index=False
)

telescopios.to_csv(
    "telescopio.csv",
    index=False
)

descubrimientos.to_csv(
    "descubrimiento.csv",
    index=False
)

"""![Diagrama del modelo relacional a construir](diagrama_relacional.png)

# **CEAR LA BASE DE DATOS RELACIONAL**

## 1. Creación e inspección de la base de datos

```sql
CREATE DATABASE astronomia;

USE astronomia;

SHOW DATABASES;

SELECT DATABASE();

```

---

## 2. Tabla `estrella`

```sql
CREATE TABLE estrella (
    id_estrella INT AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    masa DECIMAL(10,4),
    radio DECIMAL(10,4),
    temperatura INT,

    PRIMARY KEY (id_estrella),

    UNIQUE (nombre)
);

```

### Descripción de campos:

* **`id_estrella`** → Clave Primaria (PK)
* **`nombre`** → Nombre de la estrella
* **`masa`** → Masas solares ($M_\odot$)
* **`radio`** → Radios solares ($R_\odot$)
* **`temperatura`** → Temperatura efectiva ($K$)

```sql
DESCRIBE estrella;

```

---

## 3. Tabla `planeta`

```sql
CREATE TABLE planeta (
    id_planeta INT AUTO_INCREMENT,
    id_estrella INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    masa DECIMAL(12,5),
    radio DECIMAL(10,5),
    periodo_orbital DECIMAL(15,6),
    semieje_mayor DECIMAL(15,6),

    PRIMARY KEY (id_planeta),

    UNIQUE (nombre),

    FOREIGN KEY (id_estrella)
        REFERENCES estrella(id_estrella)
);

```

### Claves foráneas:

* `FOREIGN KEY (id_estrella) REFERENCES estrella(id_estrella)`

---

## 4. Tabla `telescopio`

```sql
CREATE TABLE telescopio (
    id_telescopio INT AUTO_INCREMENT,
    nombre VARCHAR(150),
    instalacion VARCHAR(150),
    instrumento VARCHAR(150),

    PRIMARY KEY (id_telescopio)
);

```

```sql
DESCRIBE telescopio;

```

---

## 5. Tabla `descubrimiento`

```sql
CREATE TABLE descubrimiento (
    id_descubrimiento INT AUTO_INCREMENT,
    id_planeta INT NOT NULL,
    id_telescopio INT,
    año INT,
    metodo VARCHAR(100),

    PRIMARY KEY (id_descubrimiento),

    FOREIGN KEY (id_planeta)
        REFERENCES planeta(id_planeta),

    FOREIGN KEY (id_telescopio)
        REFERENCES telescopio(id_telescopio)
);

```

---

## 6. Verificación final

```sql
SHOW TABLES;

```

# CREACIÓN DE LA BASE DE DATOS Y TABLAS DESDE PYTHON

Podemos automatizar la creación de la base de datos y su estructura ejecutando comandos DDL directamente desde un script de Python usando la librería `mysql-connector-python`.

---

## 1. Instalación de la librería

Si no tienes instalada la librería en tu entorno, ejecuta primero:

```bash
#!pip install mysql-connector-python
"""

#!pip install mysql-connector-python

"""## 2. Script para la creaciónde DB.

"""

import mysql.connector
from mysql.connector import Error

# 1. Configuración de parámetros de conexión
config = {
    'host': 'mysql84',
    'user': 'root',
    'password': 'root'  # Reemplazar con tu contraseña de MySQL
}

try:
    # 2. Conexión al servidor MySQL
    conexion = mysql.connector.connect(**config)
    cursor = conexion.cursor()

    # 3. Crear la base de datos 'astronomia'
    cursor.execute("CREATE DATABASE IF NOT EXISTS astronomia;")
    cursor.execute("USE astronomia;")
    print("Base de datos 'astronomia' lista.")

    # 4. Crear tabla ESTRELLA (Padre)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS estrella (
        id_estrella INT AUTO_INCREMENT,
        nombre VARCHAR(100) NOT NULL,
        masa DECIMAL(10,4),
        radio DECIMAL(10,4),
        temperatura INT,
        PRIMARY KEY (id_estrella),
        UNIQUE (nombre)
    );
    """)

    # 5. Crear tabla TELESCOPIO (Padre)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS telescopio (
        id_telescopio INT AUTO_INCREMENT,
        nombre VARCHAR(150),
        instalacion VARCHAR(150),
        instrumento VARCHAR(150),
        PRIMARY KEY (id_telescopio)
    );
    """)

    # 6. Crear tabla PLANETA (Hijo de estrella)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS planeta (
        id_planeta INT AUTO_INCREMENT,
        id_estrella INT NOT NULL,
        nombre VARCHAR(100) NOT NULL,
        masa DECIMAL(12,5),
        radio DECIMAL(10,5),
        periodo_orbital DECIMAL(15,6),
        semieje_mayor DECIMAL(15,6),
        PRIMARY KEY (id_planeta),
        UNIQUE (nombre),
        FOREIGN KEY (id_estrella) REFERENCES estrella(id_estrella)
    );
    """)

    # 7. Crear tabla DESCUBRIMIENTO (Hijo de planeta y telescopio)
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS descubrimiento (
        id_descubrimiento INT AUTO_INCREMENT,
        id_planeta INT NOT NULL,
        id_telescopio INT,
        año INT,
        metodo VARCHAR(100),
        PRIMARY KEY (id_descubrimiento),
        FOREIGN KEY (id_planeta) REFERENCES planeta(id_planeta),
        FOREIGN KEY (id_telescopio) REFERENCES telescopio(id_telescopio)
    );
    """)

    print("Todas las tablas fueron creadas exitosamente respetando la integridad referencial.")

except Error as e:
    print(f"Error al conectar o ejecutar comandos en MySQL: {e}")

finally:
    # 8. Cierre de cursores y conexión
    if 'conexion' in locals() and conexion.is_connected():
        cursor.close()
        conexion.close()
        print("Conexión a MySQL cerrada.")

"""# **INSERCION DE LOS DATOS DESDE PYTHON**

# Orden de Inserción e Integridad Referencial

En el diseño y gestión de bases de datos relacionales existe un principio fundamental: la **integridad referencial**. Esta regla establece que una clave foránea (`FOREIGN KEY`) siempre debe apuntar a un registro que ya exista previamente en la tabla de origen (`PRIMARY KEY`).

---

## 1. La Regla del "Padre antes que el Hijo"

En un modelo relacional, las tablas se clasifican según sus dependencias:

* **Tablas Padres (Independientes):** No requieren de otras tablas para existir.
* **Tablas Hijas (Dependientes):** Contienen claves foráneas que referencian a otras tablas.

> **Principio clave:** No se puede insertar un registro en una tabla hija si el identificador al que hace referencia aún no existe en la tabla padre. Intentar hacerlo generará un error de violación de restricción de clave foránea (`Foreign Key Constraint Violation`).

---

## 2. Árbol de Dependencias del Sistema

Al examinar las relaciones de la base de datos de exoplanetas:

```text
  [ ESTRELLA ]       [ TELESCOPIO ]   <--- Tablas Padres (Independientes)
       │                   │
       ▼                   │
   [ PLANETA ]             │          <--- Tabla Hija de Estrella / Padre de Descubrimiento
       │                   │
       └─────────┬─────────┘
                 ▼
          [ DESCUBRIMIENTO ]          <--- Tabla Hija dependiente de Planeta y Telescopio

```

* **`estrella`**: Es totalmente independiente (Padre).
* **`telescopio`**: Es totalmente independiente (Padre).
* **`planeta`**: Depende directamente de `estrella` a través de `id_estrella`.
* **`descubrimiento`**: Depende simultáneamente de `planeta` (`id_planeta`) y `telescopio` (`id_telescopio`).

---

## 3. Orden Lógico de Ejecución (`INSERT`)

Siguiendo la jerarquía de dependencias, el orden estricto para poblar las tablas es:

1. **`estrella`** → Debe registrarse primero la estrella hospedadora (ej. *Kepler-186*).
2. **`telescopio`** → Debe registrarse el instrumento u observatorio (ej. *Kepler*). *(Los pasos 1 y 2 son intercambiables entre sí)*.
3. **`planeta`** → Requiere que el `id_estrella` asociado ya exista en la base de datos.
4. **`descubrimiento`** → Requiere que tanto el `id_planeta` como el `id_telescopio` existan previamente.

---

### Resumen

> Para registrar que el telescopio **Kepler** descubrió el exoplaneta **Kepler-186f** alrededor de la estrella **Kepler-186**, la base de datos necesita validar primero la existencia de la estrella, asociar el planeta a dicha estrella, registrar el telescopio utilizado y, finalmente, vincular ambos identificadores en la tabla de descubrimientos.
"""

#!pip install sqlalchemy pymysql

### Crear la insercion:

import pandas as pd
from sqlalchemy import create_engine

# Nota el cambio de localhost a mysql84
engine = create_engine("mysql+pymysql://root:root@mysql84:3306/astronomia")

# Leer los CSV
estrellas = pd.read_csv("estrella.csv")
telescopios = pd.read_csv("telescopio.csv")
planetas = pd.read_csv("planeta.csv")
descubrimientos = pd.read_csv("descubrimiento.csv")

# Enviar los datos a MySQL respetando el orden lógico (Padres primero)
print("Insertando estrellas...")
estrellas.to_sql(name='estrella', con=engine, if_exists='append', index=False)

print("Insertando telescopios...")
telescopios.to_sql(name='telescopio', con=engine, if_exists='append', index=False)

print("Insertando planetas...")
planetas.to_sql(name='planeta', con=engine, if_exists='append', index=False)

print("Insertando descubrimientos...")
descubrimientos.to_sql(name='descubrimiento', con=engine, if_exists='append', index=False)

print("¡Base de datos cargada con éxito! Ya puedes ejecutar tu app.py original.")

